In [7]:
import tensorflow as tf

v1 = tf.Variable(tf.random_normal([1, 2]), name="v1")
v2 = tf.Variable(tf.random_normal([2, 3]), name="v2")

init_op = tf.global_variables_initializer()
saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(v1))
    print(sess.run(v2))
    saver.save(sess, "save/model.ckpt")
    #print(saver_path)

[[-1.4283799  1.0828044]]
[[ 0.8496924  -0.858948   -0.48736244]
 [-0.97220147 -1.202857    0.88935167]]


In [8]:
print(date)

NameError: name 'date' is not defined